project:
  type: website
  output-dir: docs

website:
  title: "Harold Llauca"
  favicon: rocket-takeoff-fill.svg

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Profile
      - href: publications.qmd
        text: Publications
      - href: posts.qmd
        text: Blog

  page-footer:
    center: "© 2026 Harold Llauca"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    smooth-scroll: true

editor: visual