project:
  type: website
  output-dir: docs

website:
  title: "Harold Llauca"
  favicon: rocket-takeoff-fill.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Profile
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: CV_Harold_Llauca.pdf
        text: CV
    page-footer: "Copyright 2023, Harold Llauca"

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

