# Articles

-   **Llauca, H.,** Lavado, W.. Evaluation of the relationship between ENSO and streamflow variability in Peruvian catchments. In preparation.

-   **Llauca, H.,** Lavado, W., Arestegui, M. Constraining flood forecasting uncertainties throw streamflow data assimilation in the Tropical Andes of Peru: Case of the Vilcanota River Basin. Water. 2023; 15(22), 3944. <https://doi.org/10.3390/w15223944>.

-   **Llauca, H.,** Leon, K., Lavado, W. Construction of a daily streamflow dataset for Peru using a similarity-based regionalization approach and a hybrid modeling framework. Journal of Hydrology: Regional Studies. 2023; 47, 101381. <https://doi.org/10.1016/j.ejrh.2023.101381>.

-   Saavedra, D., Mendoza, P. A., Addor, N., **Llauca, H.**, Vargas, X. A multi-objective approach to select hydrological models and constrain structural uncertainties for climate impact assessments. Hydrological Processes. 2021; 36(1), e14446. <https://doi.org/10.1002/hyp.14446>.

-   **Llauca H.**, Lavado-Casimiro, W., Montesinos, C., Santini, W., Rau, P. PISCO HyM GR2M : A Model of Monthly Water Balance in Peru (1981--2020). Water. 2021; 13(8), 1048. <https://doi.org/10.3390/w13081048>.

-   **Llauca H.**, Lavado-Casimiro, W., Leon, K., Jimenez, J., Traverso, K., Rau, P. Assessing Near Real-Time Satellite Precipitation Products for Flood Simulations at Sub-Daily Scales in a Sparsely Gauged Watershed in Peruvian Andes. Remote Sensing. 2021; 13(4), 826. <https://doi.org/10.3390/rs13040826>.

# Conference papers

-   **Llauca, H.**, Leon, K., Lavado, W., and Felipe, O.: SONICS: A novel in-house development system for detection and forecasting potential river floods in Peru, HEPEX Workshop 2023, Norrköping, Sweden, 13--15 Sep 2023, EGU23-8144, <https://hepex.org.au/a-look-to-the-past-hepex-workshop/>.
-   **Llauca, H.**, Leon, K., Lavado, W., and Felipe, O.: SONICS: A new Peruvian hydrological dataset of simulated daily streamflow for flood monitoring and forecasting, EGU General Assembly 2023, Vienna, Austria, 24--28 Apr 2023, EGU23-8144, <https://doi.org/10.5194/egusphere-egu23-8144>.
-   **Llauca, H.**, Lavado, W., Montesinos, C., and Rau, P.: Monthly semi-distributed hydrological model at national scale in Peru, EGU General Assembly 2020, Online, 4--8 May 2020, EGU2020-3769, <https://doi.org/10.5194/egusphere-egu2020-3769>.
-   Leon, K., Acuña, J., **Llauca, H.**, Lavado, W., Suarez, W., Ordoñez, J., and Felipe, O. : Implementation of a flood forecasting system in a transboundary river basin, Peru -- Ecuador , EGU General Assembly 2020, Online, 4--8 May 2020, EGU2020-12927, <https://doi.org/10.5194/egusphere-egu2020-12927>.
-   Asurza Véliz, F. A., Traverso-Yucra, K. A., Lavado-Casimiro, W. S., Felipe-Obando, O., Montesinos-Cáceres, C. A., and **Llauca-Soto, H. O.**: Surface water resources assessment in Peru through SWAT hydrological model, EGU General Assembly 2020, Online, 4--8 May 2020, EGU2020-6308, <https://doi.org/10.5194/egusphere-egu2020-6308>.
-   Waldo, L.-C., Juan Carlos, J., **Harold, L**., Karen, L., Clara, O., Alan, L., Adrian, H., Oscar, F., Julia, A., Pedro, R., and Jorge, A.: ANDES: The first system for flash flood monitoring and forecasting in Peru, EGU General Assembly 2020, Online, 4--8 May 2020, EGU2020-3759, <https://doi.org/10.5194/egusphere-egu2020-3759>.

# Others studies

-   **Llauca Soto, H.** (2023). Asimilación de caudales observados en la modelación hidrológica subdiaria del río Vilcanota en la estación Pisac. Available at <https://hdl.handle.net/20.500.12542/2613>.

-   **Llauca Soto, H.** (2023). Asimilación de caudales observados en la modelación hidrológica subdiaria del río Vilcanota en la estación Pisac. Available at <https://hdl.handle.net/20.500.12542/2613>.

-   Cornejo Ruiz, C., **Llauca Soto, H.** (2022). Aplicación de productos de precipitación estimada por satélite en la representación de la respuesta hidrológica de la cuenca Puyango. Available at <https://repositorio.untumbes.edu.pe/handle/20.500.12874/64626>.

-   **Llauca Soto, H.** (2018). Exploración del sensoramiento remoto en el rango de las microondas y su relación con el equivalente de agua nieve en los Andes Centrales de Chile. Available at [https://repositorio.uchile.cl/handle/2250/167759](#0).

-   **Llauca Soto, H.** (2014). Estudio del balance hídrico superficial de las cuencas del Anya y del Mchique, departamento de Junín - Perú. Available at [http://repositorio.lamolina.edu.pe/handle/20.500.12996/1833](#0).
